### ISSUE TITLE
Dropping words from batches

### ISSUE THREAD

**Issue by bmschmidt** [Bookworm-project/Hathitrust-Bookworm#4]
I'm a little worried about one thing from the notebook, if I understand what it's saying

> If a word doesn't occur at least twice in a batch of 400 texts (i.e. 2/180m words), it is trimmed from that batch. This cuts the size considerably.

I'm worried that this might be too aggressive. A lot of the current words are just about at that threshold of 1 per 90million ; won't the result of this be to keep rare words with high tf-idf, and discard rare ones with low tf-idf? That seems arbitrary. How big is the performance gain?

**Comment by organisciak** [comment]
Words that occur 1/90million would stay in the full collection, unless they were perfectly evenly distributed across the corpus. How common would it be for a word that rare to have a low idf - i.e. to occur once in every 400th book rather than 2 or 3 times in every 1000th book? Also, unless our sampling got impossibly lucky, the books where the 1word/400books occurred would not be alone in batches for the most part.

If you're worried, I can a) turn it off or b) increase the batch size. The performance of IO is excruciating in comparison to how fast all the processing it (speeding to a red light), and filtering out all that single-occurrance junk OCR trims the output by about half. Turning it off and being slightly more patient is something I can live with.

**Comment by bmschmidt** [comment]
> How common would it be for a word that rare to have a low idf - i.e. to occur once in every 400th book rather than 2 or 3 times in every 1000th book.

Pretty common, I think. Here are the Hathi wordcount numbers (generated by a method like this one in the past, which confounds things a bit), the actual counts in bookworm hathipd, and the number of books they occur in hathi_pd.

For rare-ish words (those right around this threshold) they seem to occur on average less than twice per book but more than once. The problem may be more acute in compound words that show up more in German than other languages; more than 80% of the occurences of `muhulöser` and `vielbewunderte` are the only single occurrence in their book.

```
MariaDB [hathipd]> SELECT w.wordid,w.word,w.count hathi_wordcount, sum(b.count) count_in_books, COUNT(DISTINCT bookid) distinct_books, SUM(IF(b.count=1,1,0)) books_with_one_occurrence,  sum(b.count)/COUNT(DISTINCT bookid) times_per_book  FROM words w JOIN master_bookcounts b ON w.wordid=b.wordid WHERE ABS(w.wordid-1600000) < 100000 AND MOD(w.wordid,10000)=0 GROUP BY w.wordid;
+---------+------------------------+-----------------+----------------+----------------+---------------------------+----------------+
| wordid  | word                   | hathi_wordcount | count_in_books | distinct_books | books_with_one_occurrence | times_per_book |
+---------+------------------------+-----------------+----------------+----------------+---------------------------+----------------+
| 1510000 | поборниковъ            |            5153 |           8215 |           5891 |                      4453 |         1.3945 |
| 1520000 | thereafterwards        |            5106 |           7951 |           4079 |                      2912 |         1.9493 |
| 1530000 | замечены               |            5061 |           7693 |           4501 |                      3016 |         1.7092 |
| 1540000 | ib¡                    |            5016 |           8047 |           4988 |                      3683 |         1.6133 |
| 1550000 | покойния               |            4971 |           6713 |            729 |                       149 |         9.2085 |
| 1560000 | Europa'                |            4928 |           7758 |           6260 |                      5471 |         1.2393 |
| 1570000 | LEITE                  |            4885 |           7508 |           2744 |                      1775 |         2.7362 |
| 1580000 | PHOSPHATIC             |            4842 |           7500 |           3916 |                      2584 |         1.9152 |
| 1590000 | 'stat                  |            4801 |           7664 |           4243 |                      3520 |         1.8063 |
| 1600000 | Creteil                |            4760 |           7419 |           4317 |                      2960 |         1.7186 |
| 1610000 | müheloser              |            4718 |           7535 |           6951 |                      6489 |         1.0840 |
| 1620000 | lou»                   |            4677 |           7900 |           4548 |                      3715 |         1.7370 |
| 1630000 | d’idée                 |            4637 |           7829 |           5693 |                      4415 |         1.3752 |
| 1640000 | Albicini               |            4598 |           7253 |           2907 |                      1745 |         2.4950 |
| 1650000 | LAWRY                  |            4560 |           7137 |           1503 |                       828 |         4.7485 |
| 1660000 | platinum-foil          |            4521 |           6945 |           2818 |                      1593 |         2.4645 |
| 1670000 | fracturis              |            4484 |           6787 |           2838 |                      1932 |         2.3915 |
| 1680000 | 24,354                 |            4447 |           7163 |           5715 |                      4829 |         1.2534 |
| 1690000 | vielbewunderte         |            4410 |           7065 |           6453 |                      5943 |         1.0948 |
+---------+------------------------+-----------------+----------------+----------------+---------------------------+----------------+
```

**Comment by bmschmidt** [comment]
Skimming at the code, it seems like if I/O on pandas data tables is the problem, increasing batch size might help a lot, no? (I'd imagine file size would be `O(log(batch_size))`? So could (if you're not doing it already) sorting the Hathi textid list by language before sending them to the workers.

Apologies if I'm being too obtuse. Only just noticed that you're only doing the dropping for English, so the point about German is off base.

**Comment by organisciak** [comment]
I'm not sure why increasing batch size would help in that regard? It somewhat helps with the global counts (for feeding into the word list) because I can fold those (lang x token x count), but I'm also writing out the volume level counts, volid x token x count, which will stay the same size no matter what.

By the way, I'm using the HDF5Store because it's seemed much faster than CSV. I started with the much more elegant map-reduce approach of have the individual engines crunch the data one doc at a time, then bringing it together, reducing it, and saving to disk. The reducing step took forever because it had to write gigabytes of data each time, which is why I refactored so that each engine crunches a batch of texts and writes to disk from its own process. That works faster, though I worry that with too large of a batch size, the multiple processes writing to disk would start blocking each other.

**Comment by bmschmidt** [comment]
I think I'm confused. If you're also writing out the volume level counts, I would have thought I/O on the global counts would be relatively insignificant. But I can check myself out of this conversation; suffice it to say I think some performance hit is worth it to avoid the unpredictability of the dropping interacting with TF-IDF in ways  don't fully understand.

**Comment by organisciak** [comment]
You're right. These assumptions were from when I thought I would do two passes (first global, then the doc counts) and before I started compressing the output. Might as well keep everything now. I also chose the compression algorithm for speed, but compression rate might have been a trivially better criterium.
